#!/usr/bin/env python3

import rclpy
from geometry_msgs.msg import Twist
from rclpy.node import Node
from Rosmaster_Lib import Rosmaster


def map_range(value: float, in_min: float, in_max: float, out_min: float, out_max: float) -> float:
    """
    Maps a value from an input range to an output range with clamping.
    """
    # Prevent division by zero if input range is zero. In this case, return the midpoint of the output range.
    if in_min == in_max:
        return float(out_max - out_min)

    mapped_value = out_min + ((value - in_min) * (out_max - out_min)) / (in_max - in_min)

    # Prevent values from exceeding the output bounds
    lower_bound = min(out_min, out_max)
    upper_bound = max(out_min, out_max)

    return max(lower_bound, min(mapped_value, upper_bound))


class DriveController(Node):
    """ROS 2 node that calculates and sets ESC throttle commands."""

    def __init__(self) -> None:
        super().__init__("drive_controller")
        self.robot_: Rosmaster = Rosmaster(car_type=4)

        self.declare_parameters(
            namespace="",
            parameters=[
                ("esc_min_angle", 80),
                ("esc_neutral_angle", 90),
                ("esc_max_angle", 100),
                ("clamp_esc_angle", True),
            ],
        )

        self.esc_min_angle_: int = self.get_parameter("esc_min_angle").value
        self.esc_max_angle_: int = self.get_parameter("esc_max_angle").value

        self.joystick_sub_ = self.create_subscription(Twist, "/cmd_vel", self.cmd_vel_cb, 5)
        self.get_logger().info("Drive Control Initialized.")

    def cmd_vel_cb(self, msg: Twist) -> None:
        """
        Convert linear velocity input into ESC angle.

        Args:
            msg: Command velocity message.
        """
        esc_angle: float = map_range(
            msg.linear.x, -1.0, 1.0, self.esc_max_angle_, self.esc_min_angle_
        )

        self.get_logger().info(f"Setting ESC servo angle to {esc_angle}")
        self.robot_.set_pwm_servo(servo_id=2, angle=esc_angle)

    def cleanup(self) -> None:
        """Return the ESC to neutral before shutting down the node."""
        self.robot_.set_pwm_servo(servo_id=2, angle=self.esc_neutral_angle_)


def main(args=None) -> None:
    rclpy.init(args=args)
    node = DriveController()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.cleanup()
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
